server:
  port: 8080

spring:
  application:
    name: petshop-backend
  jackson:
    time-zone: America/Bogota
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/petshop_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Bogota

jwt:
  secret: ${JWT_SECRET:bXlfc3VwZXJfc2VjcmV0X2tleV9mb3JfcGV0c2hvcF9hcGlfZm9yX3VuaXZlcnNpdHlfcHJvamVjdF8xMjM0NTY=}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

paypal:
  client-id: ${PAYPAL_CLIENT_ID:TU_CLIENT_ID_AQUI}
  client-secret: ${PAYPAL_CLIENT_SECRET:TU_SECRET_AQUI}
  mode: ${PAYPAL_MODE:sandbox}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs