server:
  port: 8080

spring:
  application:
    name: petshop-backend
  jackson:
    time-zone: America/Bogota
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/petshop_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Bogota

jwt:
  secret: ${JWT_SECRET:bXlfc3VwZXJfc2VjcmV0X2tleV9mb3JfcGV0c2hvcF9hcGlfZm9yX3VuaXZlcnNpdHlfcHJvamVjdF8xMjM0NTY=}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

paypal:
  client-id: ${Aap4YuGsATPGW-e1j2mSbxX--4A2rq6AngRz8J3oJC2ZRAjSCLESdLVAN-l-q3x3f44vMyCV3rCZuux4}
  client-secret: ${EKrNUthI_SEd2VPsMtKychgpji5q4xMyAOOCrbDbX5DVh2x7uQQ-JJagW1a4GjM-4YLRFGRVJjMKXL9X}
  mode: ${PAYPAL_MODE:sandbox}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs